#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : virt-manager
Version  : 1.5.1
Release  : 17
URL      : https://virt-manager.org/download/sources/virt-manager/virt-manager-1.5.1.tar.gz
Source0  : https://virt-manager.org/download/sources/virt-manager/virt-manager-1.5.1.tar.gz
Summary  : Desktop tool for managing virtual machines via libvirt
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: virt-manager-bin
Requires: virt-manager-data
Requires: virt-manager-license
Requires: virt-manager-locales
Requires: virt-manager-man
Requires: ipaddr-python
Requires: libosinfo
Requires: libvirt-python
Requires: osinfo-db-tools
BuildRequires : glib-bin
BuildRequires : intltool
BuildRequires : ipaddr-python
BuildRequires : libosinfo
BuildRequires : libvirt-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(gtk+-3.0)

BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: 0001-Replace-ConfigParser-with-configparser.patch
Patch2: 0002-Wrap-keys-values-in-a-list.patch
Patch3: 0003-Replace-ipaddr-module-with-ipaddress.patch
Patch4: 0004-urlfetcher-Python-2-3-compatability-for-urllib.patch
Patch5: 0005-Convert-long-to-int.patch
Patch6: 0006-Fix-re-raising-exception.patch
Patch7: 0007-Replace-Queue-with-queue.patch
Patch8: 0008-Convert-the-output-of-range-to-list.patch
Patch9: 0009-python3-compat-python3-strings-have-no-decode.patch
Patch10: 0010-Use-StringIO-instad-of-BytesIO-in-Py-3.patch
Patch11: 0011-tests-cli-Handle-UnicodeError-when-logging.patch
Patch12: 0012-Replace-raw_input-with-input.patch
Patch13: 0013-urlfetcher-Open-local-files-as-binary.patch
Patch14: 0014-Drop-python3-compat-imports.patch
Patch15: 0015-connect-Fix-urllib-usage-on-py3.patch
Patch16: 0016-Fix-initrdinject-and-urltests-with-py3.patch
Patch17: 0017-Switch-to-python3-in-script-shebang.patch
Patch18: 0018-spec-Update-for-python3.patch
Patch19: 0019-setup-Use-pylint-3.patch
Patch20: 0020-Fix-last-bits-of-python3-pylint.patch
Patch21: 0021-Update-docs-to-use-new-setup.py-invocation.patch
Patch22: 0022-spec-Remove-obsolete-icon-desktop-cache-commands.patch
Patch23: 0023-xmlbuilder-drop-is_build-monkey-patching.patch
Patch24: 0024-xmlbuilder-Drop-unused-node_top_xpath.patch
Patch25: 0025-xmlbuilder-centralize-adding-child-new-child-prop-in.patch
Patch26: 0026-Drop-__future__-imports-no-longer-needed.patch
Patch27: 0027-uitests-Silence-noisy-harmless-warnings.patch
Patch28: 0029-pylint-fix-logging-too-few-args-issue.patch
Patch29: 0030-tests-virtconvtest-Accumulate-more-errors-before-exi.patch
Patch30: 0031-virtconv-ovf-convert-to-ElementTree.patch
Patch31: 0032-Don-t-use-count-for-substring-checking.patch
Patch32: 0033-xmlbuilder-Remove-unused-code.patch
Patch33: 0034-capabilities-Move-machine-canonicalizing-to-capsinfo.patch
Patch34: 0035-Convert-docstrings-to-standard-reStructuredText-para.patch
Patch35: 0036-xmlbuilder-Remove-more-redundant-xml-state.patch
Patch36: 0037-xmlbuilder-Move-all-libxml2-interaction-to-a-single-.patch
Patch37: 0038-xmlbuilder-Move-xpath-string-ops-to-their-own-class.patch
Patch38: 0039-setup-Add-explicit-error-if-running-with-python2.patch
Patch39: 0042-tests-xmlparse-Add-qemu-xmlns-tests.patch
Patch40: 0043-tests-xmlparse-Add-a-roundtrip-metadata-test.patch
Patch41: 0045-xmlbuilder-Order-child-props-before-serializing.patch
Patch42: do-not-set-cursor.patch
Patch43: use-iso-info-command.patch

%description
Virtual Machine Manager provides a graphical tool for administering virtual
machines for KVM, Xen, and LXC. Start, stop, add or remove virtual devices,
connect to a graphical or serial console, and see resource usage statistics
for existing VMs on local or remote machines. Uses libvirt as the backend
management API.

%package bin
Summary: bin components for the virt-manager package.
Group: Binaries
Requires: virt-manager-data
Requires: virt-manager-license
Requires: virt-manager-man

%description bin
bin components for the virt-manager package.


%package data
Summary: data components for the virt-manager package.
Group: Data

%description data
data components for the virt-manager package.


%package license
Summary: license components for the virt-manager package.
Group: Default

%description license
license components for the virt-manager package.


%package locales
Summary: locales components for the virt-manager package.
Group: Default

%description locales
locales components for the virt-manager package.


%package man
Summary: man components for the virt-manager package.
Group: Default

%description man
man components for the virt-manager package.


%prep
%setup -q -n virt-manager-1.5.1
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1
%patch11 -p1
%patch12 -p1
%patch13 -p1
%patch14 -p1
%patch15 -p1
%patch16 -p1
%patch17 -p1
%patch18 -p1
%patch19 -p1
%patch20 -p1
%patch21 -p1
%patch22 -p1
%patch23 -p1
%patch24 -p1
%patch25 -p1
%patch26 -p1
%patch27 -p1
%patch28 -p1
%patch29 -p1
%patch30 -p1
%patch31 -p1
%patch32 -p1
%patch33 -p1
%patch34 -p1
%patch35 -p1
%patch36 -p1
%patch37 -p1
%patch38 -p1
%patch39 -p1
%patch40 -p1
%patch41 -p1
%patch42 -p1
%patch43 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1529028082
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/virt-manager
cp COPYING %{buildroot}/usr/share/doc/virt-manager/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
%find_lang virt-manager

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/virt-clone
/usr/bin/virt-convert
/usr/bin/virt-install
/usr/bin/virt-manager
/usr/bin/virt-xml

%files data
%defattr(-,root,root,-)
%exclude /usr/share/glib-2.0/schemas/gschemas.compiled
%exclude /usr/share/icons/hicolor/icon-theme.cache
/usr/share/GConf/gsettings/org.virt-manager.virt-manager.convert
/usr/share/appdata/virt-manager.appdata.xml
/usr/share/applications/virt-manager.desktop
/usr/share/glib-2.0/schemas/org.virt-manager.virt-manager.gschema.xml
/usr/share/icons/hicolor/16x16/apps/virt-manager.png
/usr/share/icons/hicolor/22x22/apps/virt-manager.png
/usr/share/icons/hicolor/24x24/apps/virt-manager.png
/usr/share/icons/hicolor/256x256/apps/virt-manager.png
/usr/share/icons/hicolor/32x32/apps/virt-manager.png
/usr/share/icons/hicolor/48x48/apps/virt-manager.png
/usr/share/virt-manager/icons/hicolor/16x16/actions/icon_console.png
/usr/share/virt-manager/icons/hicolor/16x16/actions/vm_new.png
/usr/share/virt-manager/icons/hicolor/22x22/actions/icon_console.png
/usr/share/virt-manager/icons/hicolor/22x22/actions/icon_details.png
/usr/share/virt-manager/icons/hicolor/22x22/actions/vm_new.png
/usr/share/virt-manager/icons/hicolor/22x22/devices/device_cpu.png
/usr/share/virt-manager/icons/hicolor/22x22/devices/device_mem.png
/usr/share/virt-manager/icons/hicolor/22x22/devices/device_pci.png
/usr/share/virt-manager/icons/hicolor/22x22/devices/device_serial.png
/usr/share/virt-manager/icons/hicolor/22x22/devices/device_usb.png
/usr/share/virt-manager/icons/hicolor/22x22/status/state_paused.png
/usr/share/virt-manager/icons/hicolor/22x22/status/state_running.png
/usr/share/virt-manager/icons/hicolor/22x22/status/state_shutoff.png
/usr/share/virt-manager/icons/hicolor/24x24/actions/icon_console.png
/usr/share/virt-manager/icons/hicolor/24x24/actions/vm_clone_wizard.png
/usr/share/virt-manager/icons/hicolor/24x24/actions/vm_new.png
/usr/share/virt-manager/icons/hicolor/32x32/actions/icon_console.png
/usr/share/virt-manager/icons/hicolor/32x32/actions/vm_new.png
/usr/share/virt-manager/icons/hicolor/32x32/status/state_paused.png
/usr/share/virt-manager/icons/hicolor/32x32/status/state_running.png
/usr/share/virt-manager/icons/hicolor/32x32/status/state_shutoff.png
/usr/share/virt-manager/icons/hicolor/48x48/actions/vm_clone_wizard.png
/usr/share/virt-manager/icons/hicolor/48x48/actions/vm_delete_wizard.png
/usr/share/virt-manager/icons/hicolor/48x48/actions/vm_import_wizard.png
/usr/share/virt-manager/icons/hicolor/48x48/actions/vm_new_wizard.png
/usr/share/virt-manager/ui/about.ui
/usr/share/virt-manager/ui/addhardware.ui
/usr/share/virt-manager/ui/addstorage.ui
/usr/share/virt-manager/ui/asyncjob.ui
/usr/share/virt-manager/ui/choosecd.ui
/usr/share/virt-manager/ui/clone.ui
/usr/share/virt-manager/ui/connect.ui
/usr/share/virt-manager/ui/create.ui
/usr/share/virt-manager/ui/createinterface.ui
/usr/share/virt-manager/ui/createnet.ui
/usr/share/virt-manager/ui/createpool.ui
/usr/share/virt-manager/ui/createvol.ui
/usr/share/virt-manager/ui/delete.ui
/usr/share/virt-manager/ui/details.ui
/usr/share/virt-manager/ui/fsdetails.ui
/usr/share/virt-manager/ui/gfxdetails.ui
/usr/share/virt-manager/ui/host.ui
/usr/share/virt-manager/ui/manager.ui
/usr/share/virt-manager/ui/migrate.ui
/usr/share/virt-manager/ui/netlist.ui
/usr/share/virt-manager/ui/preferences.ui
/usr/share/virt-manager/ui/snapshots.ui
/usr/share/virt-manager/ui/storagebrowse.ui
/usr/share/virt-manager/ui/storagelist.ui
/usr/share/virt-manager/virt-clone
/usr/share/virt-manager/virt-convert
/usr/share/virt-manager/virt-install
/usr/share/virt-manager/virt-manager
/usr/share/virt-manager/virt-xml
/usr/share/virt-manager/virtManager/__init__.py
/usr/share/virt-manager/virtManager/__pycache__/__init__.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/about.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/addhardware.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/addstorage.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/asyncjob.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/baseclass.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/choosecd.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/clone.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/config.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/connect.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/connectauth.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/connection.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/console.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/create.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/createinterface.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/createnet.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/createpool.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/createvol.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/delete.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/details.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/domain.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/engine.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/error.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/fsdetails.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/gfxdetails.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/graphwidgets.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/host.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/inspection.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/interface.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/keyring.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/libvirtobject.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/manager.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/mediacombo.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/migrate.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/module_trace.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/netlist.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/network.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/nodedev.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/packageutils.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/preferences.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/serialcon.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/snapshots.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/sshtunnels.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/storagebrowse.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/storagelist.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/storagepool.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/systray.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/uiutil.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/viewers.cpython-36.pyc
/usr/share/virt-manager/virtManager/__pycache__/vmmenu.cpython-36.pyc
/usr/share/virt-manager/virtManager/about.py
/usr/share/virt-manager/virtManager/addhardware.py
/usr/share/virt-manager/virtManager/addstorage.py
/usr/share/virt-manager/virtManager/asyncjob.py
/usr/share/virt-manager/virtManager/baseclass.py
/usr/share/virt-manager/virtManager/choosecd.py
/usr/share/virt-manager/virtManager/clone.py
/usr/share/virt-manager/virtManager/config.py
/usr/share/virt-manager/virtManager/connect.py
/usr/share/virt-manager/virtManager/connectauth.py
/usr/share/virt-manager/virtManager/connection.py
/usr/share/virt-manager/virtManager/console.py
/usr/share/virt-manager/virtManager/create.py
/usr/share/virt-manager/virtManager/createinterface.py
/usr/share/virt-manager/virtManager/createnet.py
/usr/share/virt-manager/virtManager/createpool.py
/usr/share/virt-manager/virtManager/createvol.py
/usr/share/virt-manager/virtManager/delete.py
/usr/share/virt-manager/virtManager/details.py
/usr/share/virt-manager/virtManager/domain.py
/usr/share/virt-manager/virtManager/engine.py
/usr/share/virt-manager/virtManager/error.py
/usr/share/virt-manager/virtManager/fsdetails.py
/usr/share/virt-manager/virtManager/gfxdetails.py
/usr/share/virt-manager/virtManager/graphwidgets.py
/usr/share/virt-manager/virtManager/host.py
/usr/share/virt-manager/virtManager/inspection.py
/usr/share/virt-manager/virtManager/interface.py
/usr/share/virt-manager/virtManager/keyring.py
/usr/share/virt-manager/virtManager/libvirtobject.py
/usr/share/virt-manager/virtManager/manager.py
/usr/share/virt-manager/virtManager/mediacombo.py
/usr/share/virt-manager/virtManager/migrate.py
/usr/share/virt-manager/virtManager/module_trace.py
/usr/share/virt-manager/virtManager/netlist.py
/usr/share/virt-manager/virtManager/network.py
/usr/share/virt-manager/virtManager/nodedev.py
/usr/share/virt-manager/virtManager/packageutils.py
/usr/share/virt-manager/virtManager/preferences.py
/usr/share/virt-manager/virtManager/serialcon.py
/usr/share/virt-manager/virtManager/snapshots.py
/usr/share/virt-manager/virtManager/sshtunnels.py
/usr/share/virt-manager/virtManager/storagebrowse.py
/usr/share/virt-manager/virtManager/storagelist.py
/usr/share/virt-manager/virtManager/storagepool.py
/usr/share/virt-manager/virtManager/systray.py
/usr/share/virt-manager/virtManager/uiutil.py
/usr/share/virt-manager/virtManager/viewers.py
/usr/share/virt-manager/virtManager/vmmenu.py
/usr/share/virt-manager/virtcli/__init__.py
/usr/share/virt-manager/virtcli/__pycache__/__init__.cpython-36.pyc
/usr/share/virt-manager/virtcli/__pycache__/cliconfig.cpython-36.pyc
/usr/share/virt-manager/virtcli/cliconfig.py
/usr/share/virt-manager/virtconv/__init__.py
/usr/share/virt-manager/virtconv/__pycache__/__init__.cpython-36.pyc
/usr/share/virt-manager/virtconv/__pycache__/formats.cpython-36.pyc
/usr/share/virt-manager/virtconv/__pycache__/ovf.cpython-36.pyc
/usr/share/virt-manager/virtconv/__pycache__/vmx.cpython-36.pyc
/usr/share/virt-manager/virtconv/formats.py
/usr/share/virt-manager/virtconv/ovf.py
/usr/share/virt-manager/virtconv/vmx.py
/usr/share/virt-manager/virtinst/__init__.py
/usr/share/virt-manager/virtinst/__pycache__/__init__.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/capabilities.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/cli.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/clock.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/cloner.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/connection.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/cpu.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/cputune.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/device.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/deviceaudio.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicechar.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicecontroller.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicedisk.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicefilesystem.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicegraphics.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicehostdev.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/deviceinput.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/deviceinterface.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicememballoon.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicememory.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicepanic.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/deviceredirdev.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicerng.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicesmartcard.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicetpm.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicevideo.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/devicewatchdog.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/diskbackend.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/distroinstaller.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/domainblkiotune.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/domainfeatures.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/domainmemorybacking.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/domainmemorytune.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/domainnumatune.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/domainresource.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/domcapabilities.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/guest.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/hostkeymap.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/idmap.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/initrdinject.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/installer.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/interface.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/kernelupload.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/network.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/nodedev.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/osdict.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/osxml.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/pm.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/pollhelpers.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/progress.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/seclabel.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/snapshot.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/storage.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/support.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/sysinfo.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/uri.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/urlfetcher.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/util.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/xmlbuilder.cpython-36.pyc
/usr/share/virt-manager/virtinst/__pycache__/xmlnsqemu.cpython-36.pyc
/usr/share/virt-manager/virtinst/capabilities.py
/usr/share/virt-manager/virtinst/cli.py
/usr/share/virt-manager/virtinst/clock.py
/usr/share/virt-manager/virtinst/cloner.py
/usr/share/virt-manager/virtinst/connection.py
/usr/share/virt-manager/virtinst/cpu.py
/usr/share/virt-manager/virtinst/cputune.py
/usr/share/virt-manager/virtinst/device.py
/usr/share/virt-manager/virtinst/deviceaudio.py
/usr/share/virt-manager/virtinst/devicechar.py
/usr/share/virt-manager/virtinst/devicecontroller.py
/usr/share/virt-manager/virtinst/devicedisk.py
/usr/share/virt-manager/virtinst/devicefilesystem.py
/usr/share/virt-manager/virtinst/devicegraphics.py
/usr/share/virt-manager/virtinst/devicehostdev.py
/usr/share/virt-manager/virtinst/deviceinput.py
/usr/share/virt-manager/virtinst/deviceinterface.py
/usr/share/virt-manager/virtinst/devicememballoon.py
/usr/share/virt-manager/virtinst/devicememory.py
/usr/share/virt-manager/virtinst/devicepanic.py
/usr/share/virt-manager/virtinst/deviceredirdev.py
/usr/share/virt-manager/virtinst/devicerng.py
/usr/share/virt-manager/virtinst/devicesmartcard.py
/usr/share/virt-manager/virtinst/devicetpm.py
/usr/share/virt-manager/virtinst/devicevideo.py
/usr/share/virt-manager/virtinst/devicewatchdog.py
/usr/share/virt-manager/virtinst/diskbackend.py
/usr/share/virt-manager/virtinst/distroinstaller.py
/usr/share/virt-manager/virtinst/domainblkiotune.py
/usr/share/virt-manager/virtinst/domainfeatures.py
/usr/share/virt-manager/virtinst/domainmemorybacking.py
/usr/share/virt-manager/virtinst/domainmemorytune.py
/usr/share/virt-manager/virtinst/domainnumatune.py
/usr/share/virt-manager/virtinst/domainresource.py
/usr/share/virt-manager/virtinst/domcapabilities.py
/usr/share/virt-manager/virtinst/guest.py
/usr/share/virt-manager/virtinst/hostkeymap.py
/usr/share/virt-manager/virtinst/idmap.py
/usr/share/virt-manager/virtinst/initrdinject.py
/usr/share/virt-manager/virtinst/installer.py
/usr/share/virt-manager/virtinst/interface.py
/usr/share/virt-manager/virtinst/kernelupload.py
/usr/share/virt-manager/virtinst/network.py
/usr/share/virt-manager/virtinst/nodedev.py
/usr/share/virt-manager/virtinst/osdict.py
/usr/share/virt-manager/virtinst/osxml.py
/usr/share/virt-manager/virtinst/pm.py
/usr/share/virt-manager/virtinst/pollhelpers.py
/usr/share/virt-manager/virtinst/progress.py
/usr/share/virt-manager/virtinst/seclabel.py
/usr/share/virt-manager/virtinst/snapshot.py
/usr/share/virt-manager/virtinst/storage.py
/usr/share/virt-manager/virtinst/support.py
/usr/share/virt-manager/virtinst/sysinfo.py
/usr/share/virt-manager/virtinst/uri.py
/usr/share/virt-manager/virtinst/urlfetcher.py
/usr/share/virt-manager/virtinst/util.py
/usr/share/virt-manager/virtinst/xmlbuilder.py
/usr/share/virt-manager/virtinst/xmlnsqemu.py

%files license
%defattr(-,root,root,-)
/usr/share/doc/virt-manager/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/virt-clone.1
/usr/share/man/man1/virt-convert.1
/usr/share/man/man1/virt-install.1
/usr/share/man/man1/virt-manager.1
/usr/share/man/man1/virt-xml.1

%files locales -f virt-manager.lang
%defattr(-,root,root,-)

